/**
 * ECU Definitions: Bosch MD1
 * Auto-generated from ecuDefinitions.ts
 * DO NOT EDIT DIRECTLY — edit the source and regenerate
 */

import type { EcuDef } from '../ecuDefinitions'

export const Bosch_MD1_DEFINITIONS: EcuDef[] = [
  {
    id: 'md1cs004',
    name: 'Bosch MD1CS004 (VAG 2.0 TDI)',
    manufacturer: 'Bosch',
    family: 'MD1',
    // MD1CS004 = Bosch Tricore AURIX TC3xx. Used on VW/Audi/Seat/Skoda 2.0 TDI EA288 from 2019+.
    // StageX mappack for Seat Ateca 2.0 TDI 150hp confirms map locations and dimensions.
    identStrings: ['MD1CS004', 'MD1CS', 'MD1C', 'MDCS004', 'MD1'],
    fileSizeRange: [2097152, 8388608],   // 2MB – 8MB
    vehicles: ['Seat Ateca 2.0 TDI', 'VW Tiguan 2.0 TDI', 'Skoda Karoq 2.0 TDI', 'Audi Q3 2.0 TDI', 'VW T-Roc 2.0 TDI', 'VW Passat B8 2.0 TDI'],
    checksumAlgo: 'unknown',
    checksumOffset: 0,
    checksumLength: 0,
    maps: [
      {
        id: 'md1_boost_target',
        name: 'Boost Pressure Target',
        category: 'boost',
        desc: 'Turbo boost pressure request. StageX MD1CS004: maps at 0x2DE69C region.',
        signatures: [],
        sigOffset: 0,
        rows: 18, cols: 18, dtype: 'uint16', le: true,
        factor: 0.001, offsetVal: 0, unit: 'bar',
        stage1: { multiplier: 1.18 },
        stage2: { multiplier: 1.28 },
        stage3: { multiplier: 1.40, clampMax: 55000 },
        critical: true, showPreview: true,
      },
      {
        id: 'md1_fuel_quantity',
        name: 'Torque to Fuel Quantity',
        category: 'fuel',
        desc: 'Torque to injection quantity conversion. StageX MD1CS004: 4 maps at 0x3EB83E-3EC08A (18×18).',
        signatures: [],
        sigOffset: 0,
        // StageX confirmed: 18×18 for torque-to-fuel maps
        rows: 18, cols: 18, dtype: 'uint16', le: true,
        factor: 0.01, offsetVal: 0, unit: 'mg/st',
        stage1: { multiplier: 1.15 },
        stage2: { multiplier: 1.22 },
        stage3: { multiplier: 1.30, clampMax: 6500 },
        critical: true, showPreview: true,
      },
      {
        id: 'md1_injection_duration',
        name: 'Injection Duration',
        category: 'fuel',
        desc: 'Main injection duration. StageX MD1CS004: 0x41821C (22×16).',
        signatures: [],
        sigOffset: 0,
        rows: 22, cols: 16, dtype: 'uint16', le: true,
        factor: 0.023437, offsetVal: 0, unit: 'deg',
        stage1: { multiplier: 1.12 },
        stage2: { multiplier: 1.20 },
        stage3: { multiplier: 1.28 },
        critical: true, showPreview: true,
      },
      {
        id: 'md1_torque_limit',
        name: 'Engine Torque Limiter',
        category: 'torque',
        desc: 'Maximum torque ceiling. StageX MD1CS004: 12 torque limiter maps.',
        signatures: [],
        sigOffset: 0,
        rows: 8, cols: 8, dtype: 'uint16', le: true,
        factor: 0.1, offsetVal: 0, unit: 'Nm',
        stage1: { multiplier: 1.25 },
        stage2: { multiplier: 1.38 },
        stage3: { multiplier: 1.50, clampMax: 65000 },
        critical: true, showPreview: true,
      },
      {
        id: 'md1_drivers_wish',
        name: 'Drivers Wish Torque',
        category: 'torque',
        desc: 'Pedal-to-torque demand. StageX MD1CS004: 3 maps at 0x2194E2-21960E (8×13).',
        signatures: [],
        sigOffset: 0,
        rows: 8, cols: 13, dtype: 'uint16', le: true,
        factor: 0.1, offsetVal: 0, unit: 'Nm',
        stage1: { multiplier: 1.12 },
        stage2: { multiplier: 1.20 },
        stage3: { multiplier: 1.30 },
        critical: false, showPreview: true,
      },
      {
        id: 'md1_smoke_limiter',
        name: 'Smoke Limiter Map',
        category: 'smoke',
        desc: 'Smoke limitation by MAF and Lambda. StageX MD1CS004: MAF at 0x421936 (14×16), Lambda at 0x421B86-422B86 (16×16).',
        signatures: [],
        sigOffset: 0,
        // StageX: MAF smoke = 14×16, Lambda smoke = 16×16. Use 14×16 as primary (MAF-based).
        rows: 14, cols: 16, dtype: 'uint16', le: true,
        factor: 0.01, offsetVal: 0, unit: 'mg/st',
        stage1: { multiplier: 1.12 },
        stage2: { multiplier: 1.20 },
        stage3: { multiplier: 1.30, clampMax: 6500 },
        critical: true, showPreview: true,
      },
      {
        id: 'md1_rail_pressure',
        name: 'Rail Pressure Target',
        category: 'fuel',
        desc: 'Common rail pressure request. StageX MD1CS004: 18×18 maps at 0x2DE69C-2EE71A, 16×16 at 0x41E1F8-41E8CC.',
        signatures: [],
        sigOffset: 0,
        rows: 18, cols: 18, dtype: 'uint16', le: true,
        factor: 0.1, offsetVal: 0, unit: 'bar',
        stage1: { multiplier: 1.05 },
        stage2: { multiplier: 1.08 },
        stage3: { multiplier: 1.12, clampMax: 22000 },
        critical: false, showPreview: true,
      },
      {
        id: 'md1_speed_limit',
        name: 'Vehicle Speed Limiter',
        category: 'limiter',
        desc: 'Factory speed limiter.',
        signatures: [],
        sigOffset: 0,
        rows: 1, cols: 1, dtype: 'uint16', le: true,
        factor: 1, offsetVal: 0, unit: 'km/h',
        stage1: { multiplier: 1.0 },
        stage2: { multiplier: 1.0 },
        stage3: { multiplier: 1.0 },
        addonOverrides: { speedlimiter: { multiplier: 0, addend: 65535 } },
        critical: false, showPreview: false,
      },
    ],
  },
]
